title: Get to Know Bash
tagline: A portfolio of my recent work, and my most up to date resume.
description: Find the resume and work samples of Richard Bashara here.
show_downloads: true
# google_analytics:
theme: jekyll-theme-midnight
kramdown:
  input: GFM           # optional, but keeps the GitHub‑Flavored Markdown you’re already using
  escape_html: false   # <‑‑ important!