title: Midnight theme
description: Midnight is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Get to Know Bash]
tagline: [A portfolio of my recent work, and my most up to date resume.]
description: [Find the resume and work samples of Richard Bashara here.]
