title: Midnight theme
description: Midnight is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
title: [Get to Know Bash]
tagline: [A portfolio of my recent work, and my most up to date resume.]
description: [Find the resume and work samples of Richard Bashara here.]